<?php
/**
 * Created by PhpStorm.
 * User: jiaruo
 * Date: 17/2/16
 * Time: 上午10:56
 */

namespace Api\Controller;


class FarmsController extends CommonController
{
    protected $userId = null;
    protected $animalPrice = null; //聚米田庄价格
    protected $feedProce = null;//私聊价格
    protected $actricePrice = null;//激活码价格
    protected  $SupValue = '母鸡';
    protected  $SubValue = '鸡蛋';
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->animalPrice = C('animalPrice');
        $this->feedProce = C('feedProce');
        $this->actricePrice = C('actricePrice');

        if(IS_POST){
            $this->checkGet(array('token'));
            $this->userId = $this->tokenToUserId(I('post.token'));
        }
    }

    /**
     * 获得商品
     */
    public function getProducts()
    {
        $products = array(
            'animalPrice' => $this->animalPrice,
            'feedProce' => $this->feedProce,
            'actricePrice' => $this->actricePrice,
        );
        $this->echoJson($products);
    }

    /**
     * 购买牲畜
     */
   /* public function buyAnimal()
    {
        if(IS_POST){
            $time = strtotime(date('Y-m-d',time()).' 00:00:00');

            $buyNumber = M('user_animal')->where(array('userid'=>$this->userId,'create_time'=>$time))->count();

            if($buyNumber >= C('buyCycleMostNumber')){//判断今天是否购买
                $this->echoJson(-12);
            }

            $user = $this->getUser($this->userId);
            if($user['currency'] < $this->animalPrice){//货币是否足够
                $this->echoJson(-11);
            }
			
			$buyNumber = M('user_animal')->where(array('userid'=>$this->userId))->count();

			
            $resutl = M('member')->where(array('id'=>$this->userId))->setDec('currency',$this->animalPrice);
            if($this->isFalse($resutl)){
                $this->echoJson(-1);
            }
            $animalNo = $user['account'].$buyNumber + 1;
            $lifeCycle = C('lifeCycle');//生命周期
            $expiredTime = time() + $lifeCycle * 86400;
            $animalResult = M('user_animal')->add(array(
                'userid'    => $this->userId,
                'animal_on' => $animalNo,
                'create_time'   => $time,
                'expired_time'  => $expiredTime
            ));
            if($animalResult){
                addLog($this->userId,'购买水稻',1,$this->animalPrice);
                echo json_encode(array('errcode'=>10000,'msg'=>'购买水稻成功！'));exit;
            }
        }
        $this->echoJson(-1);
    }*/

    
 
	public function getPrice(){
		$market_price = M('market_price')->where(array('start'=>array('elt',date('Y-m-d'))))->order('start desc')->find();
		$this->echoJson($market_price);
		
	}
    //开地
    public function openFarm(){
        $this->checkGet(array('type'));
        $type=I('post.type');//1 绿地 2黄地 
        $animal=$type==1?C('green_farm'):C('gold_farm');
        $time = strtotime(date('Y-m-d',time()).' 00:00:00');
        if(!$animal){
             $this->echoJson('获取地数量异常');
        }

        $user = $this->getUser($this->userId);
       
        if($user['animal_num'] < $animal){//货币是否足够

            $this->echoJson('开地所需'.$this->SupValue.'不足。');
        }
        
        if($type==1){ 
            $count= M('user_farm')->where(array('userid'=>$this->userId,'type'=>1))->count();
            if($count >= 10  ){
                $this->echoJson('田庄绿地已满');
            }
        }else{ 
            $count0= M('user_farm')->where(array('userid'=>$this->userId,'type'=>1))->count();
            if($count0<10){
                $this->echoJson('请先开完所有绿地');
            }
            $count= M('user_farm')->where(array('userid'=>$this->userId,'type'=>2))->count();
            if($count>= 5){
                $this->echoJson('田庄金地已满');
            }

        }
        $resutl = M('member')->where(array('id'=>$this->userId))->setDec('animal_num',$animal);
 

        if($this->isFalse($resutl)){
            $this->echoJson(-1);
        }
        $farmResult = M('user_farm')->add(array(
                'userid'    => $this->userId,
                'type' => $type,
                'create_time'   => $time,
                'num'=>$animal,
                'egg_status'=>2
                
            ));
        if($farmResult){
            addLog($this->userId,'开'.($type==1?'绿':'金').'地'."花费{$this->SupValue}{$animal}只",4,$animal);
            echo json_encode(array('errcode'=>10000,'msg'=>'开地成功！'));exit;
        }

 
        $this->echoJson(-1);
    }
    //土地增种稻米
    public function hatchEgg(){
        if(IS_POST){ 
            $this->checkGet(array('id','egg_num'));
            $data = I('post.'); 
            $farm= M('user_farm')->field('id,add_num,num,type')->where(array('id'=>$data['id']))->find();
            if(!$farm){
                 $this->echoJson('请指定增养土地！');
            }
            //  $data['egg_num']=(int)$data['egg_num'];
            if(!is_int($data['egg_num']+0)){
                $this->echoJson('增养数量必须是整数');
            }
            if($data['egg_num']<1){
                $this->echoJson('增养数量必须大于1');
            }
            if($farm['type']==1){
                if($farm['add_num']+$farm['num']+$data['egg_num']>3000){
                     $this->echoJson('绿地'.$this->SupValue.'总量不能超过3000');
                }
            }else{
                if($farm['add_num']+$farm['num']+$data['egg_num']>30000){
                     $this->echoJson('金地'.$this->SupValue.'总量不能超过30000');
                }
            }
            $user= M('member')->field('currency')->where(array('id'=>$this->userId))->find();
            if($user['currency'] < $data['egg_num']){
                $this->echoJson('-19');
            }

            $r1= M('member')->where(array('id'=>$this->userId))->setDec('currency',$data['egg_num']);
            if($this->isFalse($r1)){
                $this->echoJson(-1);
            }
            $r2=M('user_farm')->where(array('id'=>$data['id']))->setInc('add_num',$data['egg_num']);
            if($this->isFalse($r2)){
                $this->echoJson(-1);
            }

            $log['userid']=$this->userId;
            $log['create_time']=time();
            $log['farm_type']=$farm['type'];
            $log['number']=$data['egg_num'];
            $log['farm_id']=$data['id'];
            $log['type']=2;
            M('farm_log')->add($log);
           /* $r2=M('member')->where(array('id'=>$this->userId))->setInc('animal_num',$data['egg_num']); 
            if($this->isFalse($r2)){
                $this->echoJson(-1);
            }*/
           addLog($this->userId,"增养{$this->SubValue}{$data['egg_num']}个",5, $data['egg_num']);
           echo json_encode(array('errcode'=>10000,'msg'=>'增养成功！'));exit;
        
        }

        $this->echoJson(-1);
    }
    //增种水稻
    public function addanimal(){
        if(IS_POST){ 
            $this->checkGet(array('id','animal_num'));
            $data = I('post.'); 
            $farm= M('user_farm')->field('id,type,num,add_num')->where(array('id'=>$data['id'],'userid'=>$this->userId))->find();
            if(!$farm){
                $this->echoJson(-28);
            }
            if(!is_int($data['animal_num']+0)){
                $this->echoJson('增养数量必须是整数');
            }
            if($farm['type']==1){
                if($farm['add_num']+$farm['num']+$data['animal_num']>3000){
                     $this->echoJson('绿地'.$this->SupValue.'总量不能超过3000');
                }
            }else{
                if($farm['add_num']+$farm['num']+$data['animal_num']>30000){
                     $this->echoJson('金地'.$this->SupValue.'总量不能超过30000');
                }
            }
            $user= M('member')->field('animal_num')->where(array('id'=>$this->userId))->find();
            if($user['animal_num'] < $data['animal_num']){
                $this->echoJson('-27');
            } 
            $r1= M('member')->where(array('id'=>$this->userId))->setDec('animal_num',$data['animal_num']);
            if($this->isFalse($r1)){
                $this->echoJson(-1);
            }
            $r2=M('user_farm')->where(array('id'=>$data['id']))->setInc('add_num',$data['animal_num']); 
            if($this->isFalse($r2)){
                $this->echoJson(-1);
            }
            $log['userid']=$this->userId;
            $log['create_time']=time();
            $log['farm_type']=$farm['type'];
            $log['number']=$data['animal_num'];
            $log['farm_id']=$data['id'];
            $log['type']=1;
            M('farm_log')->add($log);
            addLog($this->userId,"增养{$this->SupValue}{$data['animal_num']}个",6, $data['animal_num']);
            echo json_encode(array('errcode'=>10000,'msg'=>'增养'.$this->SupValue.'成功！'));exit;
        }

        $this->echoJson(-1);
    }
    //收取指定土地的秧苗跟稻米。。
    public function getfarmsanimal(){
        if(IS_POST){ 
            $this->checkGet(array('id','type'));
            $data = I('post.'); 
            $farm= M('user_farm')->field('add_num,egg_rate,egg_status,egg_allrate')->where(array('id'=>$data['id'],'userid'=>$this->userId))->find();
            if(!$farm){
                $this->echoJson(-28);
            }
            if($farm['add_num']>0 && $data['type']==1){
                $r1=M('member')->where(array('id'=>$this->userId))->setInc('animal_num',$farm['add_num']);
                $r2=M('user_farm')->where(array('id'=>$data['id']))->setField('add_num',0);
                 
                if($this->isFalse($r1) || $this->isFalse($r2)){
                    $this->echoJson(-1);
                }
                addLog($this->userId,"收取{$this->SupValue}{$farm['add_num']}个",7, $farm['add_num']);
            }
            if($farm['egg_rate']<=0 && $data['type']==2){
                M('user_farm')->where(array('id'=>$data['id']))->setField('egg_status',2);
            }
            if($farm['egg_rate']>0 && $farm['egg_status']==1 && $data['type']==2){
                $save['egg_status']=2;
                $save['egg_allrate']=$farm['egg_allrate']+$farm['egg_rate'];
                $r2=M('user_farm')->where(array('id'=>$data['id']))->save($save); 
                $r1=M('member')->where(array('id'=>$this->userId))->setInc('currency',$farm['egg_rate']);
                 

                if($this->isFalse($r1) || $this->isFalse($r2)){
                    $this->echoJson(-1);
                }
                addLog($this->userId,"收取{$this->SubValue}{$farm['egg_rate']}个",8, $farm['egg_rate']);

            } 
            echo json_encode(array('errcode'=>10000,'msg'=>'打扫成功！','currency'=>$farm['egg_rate'],'aninal_num'=>$farm['add_num']));exit;
             
        }

        $this->echoJson(-1);


    }



}